### ISSUE TITLE
Image requires unnecessary(?) Linux capabilities when running as container=root, DAEMON_USER=root 

### ISSUE THREAD

**Issue by chadlwilson** [bitnami/bitnami-docker-fluentd#13]
**Description**

As noted at https://github.com/bitnami/charts/pull/2323#discussion_r440116573 when you run this image as `root` but also set `DAEMON_USER=root`, `DAEMON_GROUP=root` the start scripts still perform a number of actions requiring [special Linux capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html) which seem unnecessary.

- [[setup.sh](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/setup.sh#L25)] chowning to allow fluent plugin installs (**requires** `CAP_CHOWN`)
- [[setup.sh](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/setup.sh#L31)]  chowning to ensure log and plugins dirs have right ownership (**requires** `CAP_CHOWN`)
- [[run.sh](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/run.sh#L29)] `gosu` (**requires** `CAP_SETUID` + `CAP_SETGID`)

These three steps seem unnecessary when running
- container as `root`
- `DAEMON_USER=root`
- `DAEMON_GROUP=root`

When running the image under Kubernetes (e.g with [the BItnami chart](https://github.com/bitnami/charts/tree/master/bitnami/fluentd)) this makes the image a bit of a pain to run as `root` alongside a [`PodSecurityPolicy`](https://kubernetes.io/docs/concepts/policy/pod-security-policy/). Using a `PodSecurityPolicy` (or restricted pod/container [`securityContext`](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) allows us to limit/mitigate what the container can do with its `root` privileges as much as possible.

e.g it is common for restricted policies to do
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: fluentd-forwarder-psp
spec:
  allowedCapabilities: []
  requiredDropCapabilities:
    - ALL
  # SNIP - omitted others for clarity
```

**Proposal:**

Only run `chown`s and `gosu`s in the scripts if `DAEMON_USER != root`

**Steps to reproduce the issue:**

Under **Docker**
- chown issue `docker run --rm --name fluentd --user root:root -e FLUENTD_DAEMON_USER=root --cap-drop CHOWN bitnami/fluentd:latest`
- gosu issue `docker run --rm --name fluentd --user root:root -e FLUENTD_DAEMON_USER=root --cap-drop SETUID --cap-drop SETGID bitnami/fluentd:latest`

Under **Kubernetes**
Not so easy. :-)

1. Get access to a cluster with the `PodSecurityPolicy` admission plugin enabled
2. Remove access to any default permissive PSP
3. `helm install fluentd bitnami/fluentd --set aggregator.enabled=false,forwarder.enabled=true`
4. Define a PSP which drops all capabilities bound to the `forwarder`s `ServiceAccount`
5. `kubectl rollout restart daemonset/fluentd`

Pods should start running but
- without `CHOWN` capability - will just die with `Exit Code:    10` with no error logged
- without `SETUID`/`SETGID` capability - `gosu` will die with `Exit Code:    1` logging `error: failed switching to "root": operation not permitted`

**Describe the results you expected:**

This should work on `docker`
`docker run --rm --name fluentd --user root:root -e FLUENTD_DAEMON_USER=root --cap-drop ALL  bitnami/fluentd:latest`

i.e if running as `root` we should be able to drop all special linux capabilities and when in K8s, run with a policy that only allows
- mounting whitelisted docker hostPaths
- `runAsUser` root + `fsGroup` root

We shouldn't have to also grant it permissions to chown files (especially off the `hostPath`) and change process user IDs, since we are already running as root.

**Additional information**

- related to https://github.com/bitnami/charts/issues/1905

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input. Indeed, this container is a very special case in our catalog, and it is one of the few that we allow running it as root (without even creating a user). I will open a task for evaluating it. I cannot guarantee an ETA but I will update this ticket as soon as I have more news.

**Comment by chadlwilson** [comment]
Thanks @javsalgar - I have submitted a simple PR which I believe resolves this. I can't see a downside for this change, as I don't believe the intention of the `chown`s or `gosu`s here were to run when you are already running the container as `root`.

Likewise, if you run with `--user 1001:1001` the image start scripts don't `gosu` or attempt to check permissions of any directories, and leaves it up to the user to mount volumes appropriately. Seems it should behave similarly when trying to run totally as root.

For context as to what I am trying to do, is to help enhance the Bitnami fluentd chart so that in the short term
- it allows you to specific minimal `containerSecurityContext` to add in selecting the right PSP
- possibly bundles a minimal PodSecurityPolicy which users can optionally install when needing to run as `root`

Resolving this quirk with the Docker image would make defining/maintaining such PSPs simpler and allow reducing the permissions of the container further.
