### ISSUE TITLE
add fluent-plugin-s3 

### ISSUE THREAD

**Issue by jjo** [bitnami/bitnami-docker-fluentd#2]
It would be very useful to have `fluent-plugin-s3` available by default in our fluentd container,
as it's frequently used as logshipping sink for some log aggregation services.

FYI below `Dockerfile` builds a container that successfully reports loading the s3 plugin:
```
FROM bitnami/fluentd:1.7.4-r18
RUN fluent-gem install fluent-plugin-s3
```

**Comment by alemorcuq** [comment]
Hi, @jjo.

Thanks for the suggestion. I've added `fluent-plugin-s3` to the image and it's now available in these releases:

- 1.7.4-debian-9-r21
- 1.7.4-ol-7-r32

**Comment by jjo** [comment]
@alemorcuq how awesome is that, thanks much ! :tada:
