### ISSUE TITLE
Add rewrite-tag plugin

### ISSUE THREAD

**Issue by irizzant** [bitnami/bitnami-docker-fluentd#20]
**Description**

Is it possible to install the [rewrite tag](https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag) plugin by default? I think it is an useful addon for logs routing.

**Comment by andresbono** [comment]
Hi @irizzant, we will consider the addition of the plugin. 

Can you confirm is this one? https://rubygems.org/gems/fluent-plugin-rewrite-tag-filter

**Comment by irizzant** [comment]
Hi @andresbono yes it's that one

**Comment by andresbono** [comment]
Hi @irizzant, we added the plugin. Please use the latest version of the image:

```console
$ docker run --rm bitnami/fluentd:1.11.5-debian-10-r26 -- fluent-gem list
...
fluent-plugin-rewrite-tag-filter (2.3.0)
```

Let us know if you find any problems and we will reopen the issue.

**Comment by irizzant** [comment]
Will do, thanks
