### ISSUE TITLE
Add fluent-plugin-color-stripper plugin

### ISSUE THREAD

**Issue by gdxhsw** [bitnami/bitnami-docker-fluentd#21]
**Description**

Hi,

Is it possible to add fluent-plugin-color-stripper? it would be useful when forward logs to ElasticSearch, s3, ...etc.

- https://github.com/mattheworiordan/fluent-plugin-color-stripper

Thank you!

**Comment by miguelaeh** [comment]
Hi @gdxhsw ,
You can follow this link to extend this image by installing custom plugins: https://github.com/bitnami/bitnami-docker-fluentd#extend-this-image
