### ISSUE TITLE
FilePermissionError when extending image with plugin

### ISSUE THREAD

**Issue by ddegasperi** [bitnami/bitnami-docker-fluentd#22]
Hi ,

I've tried to extend the image by following the description of the reamde: https://github.com/bitnami/bitnami-docker-fluentd#extend-this-image to add the "fluent-plugin-azure-loganalytics" plugin and got the following error message: 

```sh
 > [2/2] RUN fluent-gem install 'fluent-plugin-azure-loganalytics':
#4 2.918 ERROR:  While executing gem ... (Gem::FilePermissionError)
#4 2.918     You don't have write permissions for the /opt/bitnami/fluentd/bin directory.
```

Can it be that by switching to `USER 1001` adding plugin is no longer possible?

Best regards

**Comment by juan131** [comment]
Hi @ddegasperi 

The image is a non-root container (user is a non-privileged user `1001` by default), see https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/Dockerfile#L29


Therefore, you lack of permission to perform the `fluent-gem install` action. You can workaround using a Dockerfile like the on below:

```Dockerfile
FROM bitnami/fluentd:1

## Change user to perform privileged actions
USER 0
## Perform "privileged" actions
RUN fluent-gem install ...
## Revert to the original non-root user
USER 1001
```

**Comment by ddegasperi** [comment]
Hi @juan131 ,

thanks, that worked. Is there any chance, that this plugin "fluent-plugin-azure-loganalytics" will be added to the bitnami/fluentd image?

Best regards

**Comment by juan131** [comment]
Hi @ddegasperi 

> thanks, that worked

Great, I'm glad the workaround worked!

> Is there any chance, that this plugin "fluent-plugin-azure-loganalytics" will be added to the bitnami/fluentd image?

It's true that the plugin barley adds 2MB to the image, but it's quite a very specific plugin for a very concrete use case: using Fluentd to aggregate data and write it to Azure Log Analytics.

We'd like to keep this image as generic and cloud-agnostic as possible.

**Comment by ddegasperi** [comment]
| We'd like to keep this image as generic and cloud-agnostic as possible.

Of course I understand this decision and will continue with the extended image. Thanks
