### ISSUE TITLE
update fluent-plugin-elasticsearch to 4.3 to enable elastic cloud

### ISSUE THREAD

**Issue by FireFart** [bitnami/bitnami-docker-fluentd#23]
Please see also here https://github.com/bitnami/charts/issues/4792

Currently we use fluent-plugin-elasticsearch 4.2.2, the latest as the time of writing is 4.3.3.

Version 4.3 introduced support for elastics own cloud service:
https://github.com/uken/fluent-plugin-elasticsearch/commit/baf866668097179b119f752e4d3ee869b7e6f746

Would be great if you can update the gem to the latest version so it's possible to use `cloud_id` and `cloud_auth` in the config

**Comment by FireFart** [comment]
Image was updated

**Comment by rafariossaa** [comment]
Hi, thanks for realizing that.
I hope that makes it for you.
