### ISSUE TITLE
Cannot run fluentd aggregator as root

### ISSUE THREAD

**Issue by chetanv-oi** [bitnami/bitnami-docker-fluentd#24]
This looks like a typo:

https://github.com/bitnami/bitnami-docker-fluentd/blob/4acc1fa39c1601dc100b3ae137e9e6b240381b5d/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/run.sh#L29

s/infod/info/ ?

**Comment by juan131** [comment]
Correct! It's totally a typo. Thanks for reporting it @chetanv-oi 
Would you submit a PR to fix it?

**Comment by chetanv-oi** [comment]
https://github.com/bitnami/bitnami-docker-fluentd/pull/25

**Comment by juan131** [comment]
Your PR was merged, please wait for a new revision of the container to be released during the following hours including your changes.
