### ISSUE TITLE
Add gcs output plugin

### ISSUE THREAD

**Issue by Ajarmar** [bitnami/bitnami-docker-fluentd#26]
Hi, would it be possible to add the [`fluent-plugin-gcs` output plugin](https://github.com/daichirata/fluent-plugin-gcs)? I've seen that you have instructions for extending the image, just curious if the plugin is small enough that you'd consider adding it to your base image. Would be great for running fluentd on GCP.

**Comment by migruiz4** [comment]
Hi @Ajarmar,

We try to keep our images the minimal size and we track closely all the components included in them looking for potential vulnerabilities, for that reason our images include the minimum required plugins and packages and we try to provide the instructions for users to include them.

Although, if a plugin is widely used and we see its popularity/demand increasing in our community, we may consider adding it if it has a reasonable size.
