### ISSUE TITLE
QQ

### ISSUE THREAD

**Issue by jliao2011** [bitnami/bitnami-docker-fluentd#27]
Hi, I was wondering if you image was intended only for use for printing to stdout? I would like to use to image and with type @http and send data to splunk but I seem to permanently get a 400 unmarshalling error, is there anyway to request that you guys include the splunk_hec plugin and the fluent-plugin-out-http? Thanks for the time

**Comment by alemorcuq** [comment]
Hi, @jliao2011. Our image is not intended only for printing to stdout. It includes some plugins by default, while others have to be installed by the users. We usually don't add any plugins to the image unless there is a high demand for them, as adding many plugins increases the maintenance cost of the image and the potential vulnerabilities that can be found.

However, you can extend the image yourself to install any plugins you need.
