### ISSUE TITLE
Add CRI plugin (fluent-plugin-parser-cri) by default

### ISSUE THREAD

**Issue by jeicob22** [bitnami/bitnami-docker-fluentd#29]
As the usage of containerd is becoming more and more extended in Kubernetes, It may have sense to include the CRI plugin by default in the base image in order to be able to properly parse the logs.
Right now, a workaround is to create a custom image adding the "fluent-plugin-parser-cri". Example:
```Dockerfile
FROM bitnami/fluentd:1.14.2-debian-10-r0

RUN gem install fluent-plugin-parser-cri --no-document
```

Because of this, probably it could have sense to add this plugin by default on the base image.

**Comment by carrodher** [comment]
Thanks for creating the issue, we try to provide ways to add third-party plugins as you rightly are doing to avoid including this kind of customization in the image. Maintaining images as simple as possible is a good practice in terms of security, size, etc.
Being said that, I will maintain the issue openly and if there are more users requesting this plugin we can evaluate the addition by default in the image, in the end, we try to find a balance between usability and security/performance.

**Comment by jeicob22** [comment]
Hello @carrodher 
Sure! thanks for your answer. I'm completelly agree with what you say.
It's just a proposal but also if it has no sense/it's out of the scope, feel free to close it. I think that having the workaround  specified in this issue, in case somebody is looking for a similar solution for a containerd based cluster etc., would be enough.

Thanks again @carrodher !

**Comment by carrodher** [comment]
Thanks for the suggestion, as commented in the previous message, we try to avoid this kind of inclusion in the image itself but add ways to customize it

**Comment by chrisjbremner** [comment]
Yep, makes sense just adding another :+1: in case there's enough momentum to consider adding it to the base image. Since I'm using K8s, I believe I can just install this plugin with an `initContainer` so that I don't have to maintain my own image with the plugin installed.
