### ISSUE TITLE
Is it possible to configure index shard value in fluentd. ||  Fluentd version 4.4.3

### ISSUE THREAD

**Issue by ajitpalsinghjat** [bitnami/bitnami-docker-fluentd#33]
Is it possible to configure index shard value in fluentd. 

We are using below version with helm :

Fluentd version 4.4.3

**Comment by juan131** [comment]
Hi @ajitpalsinghjat 

Please refer to the [configuration](https://github.com/bitnami/bitnami-docker-fluentd#configuration) section of the README.md to find more info about how to customize Fluentd's configuration.
