### ISSUE TITLE
Add record_transformer plugin by default

### ISSUE THREAD

**Issue by kvokka** [bitnami/bitnami-docker-fluentd#34]
### Name and Version

bitnami/bluentd:latest

### What is the problem this feature will solve?

The official [fluentd docs](https://docs.fluentd.org/filter/record_transformer#need-more-performance) a forwarding us to the gem https://github.com/repeatedly/fluent-plugin-record-modifier to solve the performance issues. Imho it should be included in the image by default

### What is the feature you are proposing to solve the problem?

Add 

```Dockerfile
RUN fluent-gem install 'fluent-plugin-record-modifier'
```

to Dockerfile

### What alternatives have you considered?

Add on option some script which will allow gem installation before fluentd start instead of patching the Docker image.

Otherwise, it requires writing my own wrapper for one-liners like this.

**Comment by migruiz4** [comment]
Hi @kvokka,

Thank you for your feature request! I don't see any inconvenience in adding the `record-modifier` plugin, since it is lightweight, focused on improving the performance, and also [listed by Fluentd](https://www.fluentd.org/plugins#filter) as a verified plugin with 18M+ downloads.

We will let you know when a new version of the bitnami/fluentd image has been released including the plugin.

**Comment by kvokka** [comment]
Hi @migruiz4 

I'm happy to hear that we are looking in one direction. If it might help, I can do a PR for it to speed up the process. wdty?

**Comment by migruiz4** [comment]
I appreciate your offering to contribute! But no need to submit the PR in this case, as the plugin will be packed in Fluentd's package:
https://github.com/bitnami/bitnami-docker-fluentd/blob/90b7e8657b8f95f4d8e295ed705724ab68f7450b/1/debian-10/Dockerfile#L14

We will release `fluentd-1.14.5-2` including the plugin

**Comment by kvokka** [comment]
Wow, that is really quick! Thank you for such help :)

**Comment by migruiz4** [comment]
Hi @kvokka!

A new version of the `bitnami/fluentd`  image has been released! Starting from version `1.14.5-debian-10-r6` the 'record-modifier' plugin should be available by default.

If you find any further issue please let me know.
