### ISSUE TITLE
Add fluent-plugin-datadog

### ISSUE THREAD

**Issue by austince** [bitnami/bitnami-docker-fluentd#4]
Is it possible to add the [fluentd-datadog](https://github.com/DataDog/fluent-plugin-datadog) plugin? Or is it best to just create my own docker image based on this? Thanks!

**Comment by andresbono** [comment]
Hi @austince, we recommend you to create your own Docker image. You can use `bitnami/fluentd` as the base image.

There is a section in the _README.md_ that you may find useful for your purpose: [Customize this image
](https://github.com/bitnami/bitnami-docker-fluentd#customize-this-image)

Hope you find it useful!

**Comment by austince** [comment]
Perfect - apologies that I missed the readme section!

**Comment by andresbono** [comment]
No worries, @austince.
