### ISSUE TITLE
fluent-plugin-azure-storage-append-blob not working in kubernetes

### ISSUE THREAD

**Issue by vishal8k** [bitnami/bitnami-docker-fluentd#5]
**Description**

My goal is to setup fluentd daemonset in my AKS cluster and export the logs to azure blob storage using the plugin "fluent-plugin-azure-storage-append-blob"

**Steps to reproduce the issue:**

1.  Setup a config map for the azure-storage-append-blob using the following link:
   https://github.com/Microsoft/fluent-plugin-azure-storage-append-blob
Below is my configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-aksconfig
  namespace: mynamespace
data:
  fluentd.conf: |
    <match **>
          @type azure-storage-append-blob
          azure_storage_account    mystorageaccount
          azure_storage_access_key myaccesskey
          azure_container          aksfluentd
          auto_create_container    true
          path logs/
          azure_object_key_format  %{path}%{time_slice}_%{index}.log
          time_slice_format        %Y%m%d-%H
          # if you want to use %{tag} or %Y/%m/%d/ like syntax in path / azure_blob_name_format,
          # need to specify tag for %{tag} and time for %Y/%m/%d in <buffer> argument.
          <buffer tag,time>
            @type file
            path /var/log/fluent/azurestorageappendblob
            timekey 120 # 2 minutes
            timekey_wait 60
            timekey_use_utc true # use utc
          </buffer>
    </match>
```

2. Setup fluentd setup using the following link: https://github.com/bitnami/azure-marketplace-charts/tree/master/bitnami/fluentd with only change is passing the configmap above like below:

`helm install fluentd bitnami-azure/fluentd --namespace mynamespace --set forwarder.configMap=fluentd-aksconfig
`
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```Below is the error logs that I was able to obtain from the pods.

> [38;5;6mfluentd [38;5;5m09:37:33.32 [0m
> [38;5;6mfluentd [38;5;5m09:37:33.33 [0m[1mWelcome to the Bitnami fluentd container[0m
> [38;5;6mfluentd [38;5;5m09:37:33.33 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-fluentd[0m
> [38;5;6mfluentd [38;5;5m09:37:33.33 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-fluentd/issues[0m
> [38;5;6mfluentd [38;5;5m09:37:33.33 [0mSend us your feedback at [1mcontainers@bitnami.com[0m
> [38;5;6mfluentd [38;5;5m09:37:33.33 [0m
> [38;5;6mfluentd [38;5;5m09:37:33.34 [0m[38;5;2mINFO [0m ==> ** Starting Fluentd setup **
> [38;5;6mfluentd [38;5;5m09:37:33.53 [0m[38;5;2mINFO [0m ==> ** Fluentd setup finished! **
> [38;5;6mfluentd [38;5;5m09:37:33.54 [0m[38;5;2mINFO [0m ==> ** Starting Fluentd **
> 2020-02-18 09:37:34 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.13'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.1'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-kafka' version '0.12.2'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.4.2'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-s3' version '1.2.1'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
> 2020-02-18 09:37:34 +0000 [info]: gem 'fluentd' version '1.9.1'
> 2020-02-18 09:37:34 +0000 [error]: config error file="/opt/bitnami/fluentd/conf/fluentd.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'azure-storage-append-blob'. Run 'gem search -rd fluent-plugin' to find plugins"
> 

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @vishal8k ,

  This plugin is not  installed by default. You can customize the image to add it. There are some documentation about this [here](https://github.com/bitnami/bitnami-docker-fluentd#user-content-customize-this-image).

**Comment by vishal8k** [comment]
@rafariossaa  Thank you! I shall probably do that and also raise a feature request.

**Comment by vishal8k** [comment]
> Hi @vishal8k ,
> 
> This plugin is not installed by default. You can customize the image to add it. There are some documentation about this [here](https://github.com/bitnami/bitnami-docker-fluentd#user-content-customize-this-image).

Just one question here. I'm gonna edit the dockerfile and a build my own custom image. Should I also have the "entrypoint.sh" and "run.sh" files present in the repo?

**Comment by rafariossaa** [comment]
Hi @vishal8k ,
  Yes, you will need all the files provided. They are used in the Dockerfile to build the images and later when starting the container.
  I think the best approach is to clone the repo and make the changes in there.

**Comment by vishal8k** [comment]
ok. Thank you for the input. Closing this issue.
