### ISSUE TITLE
Unable to customize with custom ruby gems. 

### ISSUE THREAD

**Issue by vishal8k** [bitnami/bitnami-docker-fluentd#6]
**Description**
I want to build the fluentd image with the `fluent-plugin-azure-storage-append-blob` installed. Below is my Dockerfile. 

```
FROM bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux"

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages ca-certificates curl ghostscript imagemagick libc6 libgcc1 libgmp-dev libjemalloc-dev libncurses5-dev libncurses6 libreadline-dev libreadline7 libssl1.1 libstdc++6 libtinfo6 libxml2-dev libxslt1-dev procps sudo unzip wget zlib1g zlib1g-dev
RUN . ./libcomponent.sh && component_unpack "ruby" "2.6.5-1" --checksum 99d4bc115bd1f2ce13a76e16359f03acef2ceccfc5468f1b008e9ea9d07dc7fc
RUN . ./libcomponent.sh && component_unpack "gosu" "1.11.0-3" --checksum c18bb8bcc95aa2494793ed5a506c4d03acc82c8c60ad061d5702e0b4048f0cb1
RUN . ./libcomponent.sh && component_unpack "fluentd" "1.9.3-0" --checksum d76f66dab66b15389eb046b9c654297eb6704217bb4653dd5488e03fd99a1731
RUN apt-get update && apt-get upgrade -y && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives
RUN useradd -r -u 1001 -g root fluentd

COPY rootfs /
RUN /postunpack.sh
ENV BITNAMI_APP_NAME="fluentd" \
    BITNAMI_IMAGE_VERSION="1.9.3-debian-10-r5" \
    GEM_HOME="/opt/bitnami/fluentd" \
    PATH="/opt/bitnami/ruby/bin:/opt/bitnami/common/bin:/opt/bitnami/fluentd/bin:$PATH"
#GEM Installation
RUN fluent-gem install 'fluent-plugin-azure-storage-append-blob'

EXPOSE 24224 5140

WORKDIR /opt/bitnami/fluentd
USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]
```

**Describe the results you received:**
However Exactly in the step where the gem is to be installed I'm displayed with the below error message. 

> ERROR:  Error installing fluent-plugin-azure-storage-append-blob:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /opt/bitnami/fluentd/gems/nokogiri-1.10.9/ext/nokogiri
> /opt/bitnami/ruby/bin/ruby -I /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200318-6-lne5k.rb extconf.rb
> checking if the C compiler accepts ... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --without-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/opt/bitnami/ruby/bin/$(RUBY_BASE_NAME)
>         --help
>         --clean
> /opt/bitnami/ruby/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
>         from /opt/bitnami/ruby/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
>         from /opt/bitnami/ruby/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
>         from /opt/bitnami/ruby/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
>         from extconf.rb:138:in `nokogiri_try_compile'
>         from extconf.rb:162:in `block in add_cflags'
>         from /opt/bitnami/ruby/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'
>         from extconf.rb:161:in `add_cflags'
>         from extconf.rb:416:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /opt/bitnami/fluentd/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.9/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /opt/bitnami/fluentd/gems/nokogiri-1.10.9 for inspection.
> Results logged to /opt/bitnami/fluentd/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.9/gem_make.out

**Additional information:**
Upon googling the error message many suggested to install ruby-dev but that didn't go out well too as apt-get returned an error stating `unable to locate package ruby-dev`

I'm also not sure on how to view the `mkmf.log` file mentioned in the error as the container exits immediately after the error. Any suggestions or inputs on where I'm going wrong?

**Comment by Mauraza** [comment]
Hi @vishal8k 

this gem you need to add` build-essential ` so you need to add in the Dockerfile. 
The Dockerfile will be:
```
FROM bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux"

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages ca-certificates curl ghostscript imagemagick libc6 libgcc1 libgmp-dev libjemalloc-dev libncurses5-dev libncurses6 libreadline-dev libreadline7 libssl1.1 libstdc++6 libtinfo6 libxml2-dev libxslt1-dev procps sudo unzip wget zlib1g zlib1g-dev
RUN . ./libcomponent.sh && component_unpack "ruby" "2.6.5-1" --checksum 99d4bc115bd1f2ce13a76e16359f03acef2ceccfc5468f1b008e9ea9d07dc7fc
RUN . ./libcomponent.sh && component_unpack "gosu" "1.11.0-3" --checksum c18bb8bcc95aa2494793ed5a506c4d03acc82c8c60ad061d5702e0b4048f0cb1
RUN . ./libcomponent.sh && component_unpack "fluentd" "1.9.3-0" --checksum d76f66dab66b15389eb046b9c654297eb6704217bb4653dd5488e03fd99a1731
RUN apt-get update && apt-get upgrade -y && \
    # Add build-essential for fluent-plugin-azure-storage-append-blob
    apt-get install build-essential -y && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives
RUN useradd -r -u 1001 -g root fluentd

COPY rootfs /
RUN /postunpack.sh
ENV BITNAMI_APP_NAME="fluentd" \
    BITNAMI_IMAGE_VERSION="1.9.3-debian-10-r5" \
    GEM_HOME="/opt/bitnami/fluentd" \
    PATH="/opt/bitnami/ruby/bin:/opt/bitnami/common/bin:/opt/bitnami/fluentd/bin:$PATH"

#GEM Installation
RUN fluent-gem install 'fluent-plugin-azure-storage-append-blob'

EXPOSE 24224 5140

WORKDIR /opt/bitnami/fluentd
USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]
```
I hope that help you.

**Comment by vishal8k** [comment]
@Mauraza Will try that in a few hours and if everything goes well, Will update the thread and close the issue
