### ISSUE TITLE
where do we enter elasticsearch password?

### ISSUE THREAD

**Issue by tirelibirefe** [bitnami/bitnami-docker-fluentd#7]
where do we enter elasticsearch password?

**Comment by joancafom** [comment]
Hi @tirelibirefe, 

We offer a container using [FluentBit](https://github.com/bitnami/bitnami-docker-fluent-bit) which makes it easy to dispatch information to different outputs such as ES.

Would that work for you? Thanks!

**Comment by tirelibirefe** [comment]
Thanks @joancafom but I didn't understand how it helps. I use Kubernetes and don't want to spend extra time to use/configure a specific container.
I switched to stable/fluent-bit helm chart, it works smoothly.

**Comment by joancafom** [comment]
Oh, in case you use K8s just to let you know we also provide a [Fluentd helm chart](https://github.com/bitnami/charts/tree/master/bitnami/fluentd) in case you want to check it out. Redirection to ElasticSearh is also addressed in the [README](https://github.com/bitnami/charts/tree/master/bitnami/fluentd#forwarding-the-logs-to-another-service).

Thanks for your issue 😁
