### ISSUE TITLE
Removal of mapping_types

### ISSUE THREAD

**Issue by irizzant** [bitnami/bitnami-docker-fluentd#8]
**Description**

-------------------------------
    BUG REPORT INFORMATION
-------------------------------
 Fluentd is producing a lot of deprecation warnings:
`warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."`

**Steps to reproduce the issue:**
1. Start fluentd and send logs to elasticsearch v 7.8.0
1. Inspect fluentd logs

**Describe the results you received:**

Fluentd is producing the warnings above

**Describe the results you expected:**

Fluentd should not produce the warnings above

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/uken/fluent-plugin-elasticsearch/releases/tag/v4.0.10 should fix this

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-109-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.21GiB
 Name: pclnxdev22
 ID: D372:OWDS:SZT3:OLYW:XB77:TONZ:ELT5:QG4C:DJ3D:KKY6:2UCK:MRQB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://maven-repo.sdb.it:18080/
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the information. I will trigger  a new build of our container to see if the new plugin is included.

**Comment by irizzant** [comment]
Hi @javsalgar 
that would be very much appreciated, we have many warning logs emitted

**Comment by javsalgar** [comment]
Hi,

The latest revision of the container should contain version 4.0.10. Please let us know if you find any other issue

**Comment by irizzant** [comment]
Hi @javsalgar 
I suppose the elasticsearch plugin still does not work.

I used ` docker.io/bitnami/fluentd:1.11.1-debian-10-r15` and this is the log:
```
fluentd 08:01:49.97 INFO  ==> ** Fluentd setup finished! **
fluentd 08:01:49.97 INFO  ==> ** Starting Fluentd **
2020-07-08 08:01:50 +0000 [info]: parsing config file is succeeded path="/opt/bitnami/fluentd/conf/fluentd.conf"
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.13'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.10'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.0'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.8.1'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-s3' version '1.3.3'
2020-07-08 08:01:50 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-07-08 08:01:50 +0000 [info]: gem 'fluentd' version '1.11.1'
```

But when I send logs to Elasticsearch I get:
`warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."`

**Comment by javsalgar** [comment]
Hi,

From what I see, the container has the correct plugin, could you report it to them to see if there's anything we are missing?

**Comment by irizzant** [comment]
Hi
see https://github.com/uken/fluent-plugin-elasticsearch/issues/766

simply updating the plugin is not enough, you also have to add:
`suppress_type_name true`

in the config.
